version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/workspaces:cached
    # Keep the container running
    command: /bin/sh -c "while sleep 1000; do :; done"
    # Forward ports for Azure Functions
    ports:
      - "7071:7071"
    # Environment variables
    environment:
      DOTNET_ENVIRONMENT: Development
      GIT_USER_NAME: Jon Bramley
      GIT_USER_EMAIL: jon.bramley@hotmail.com
      AZURE_FUNCTIONS_ENVIRONMENT: Development